In [3]:
import numpy as np

In [3]:
(np.zeros((3,4,8))+5)*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [5]:
np.linspace(4,8,80)

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [6]:
l=[1,23,5,4,6,7,8,9,11,12]
mat=np.matrix(l)
mat

matrix([[ 1, 23,  5,  4,  6,  7,  8,  9, 11, 12]])

In [8]:
a = np.ones((4,5,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [12]:
print("Dimension: ",a.ndim)

Dimension:  3


In [19]:
print("Dimension: ",a.ndim,sep='')
print("Size: ",a.size,sep='')
print("Shape: ",a.shape,sep='')
print("Datatype: ",a.dtype,sep='')

Dimension: 3
Size: 40
Shape: (4, 5, 2)
Datatype: float64


In [17]:
x1=np.ones((3,3,3))
x2 = np.copy(x1)
x1+x2

array([[[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]])

In [3]:
np.array([1,2,3], ndmin=5)

array([[[[[1, 2, 3]]]]])

In [4]:
np.array([1,2,3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [7]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [11]:
np.array([(1,2),(3,4)], dtype=[('a','<i2'),('b','i4')])

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i4')])

In [12]:
a = np.array([[1,2],[3,4]])
b= np.asarray([[1,2],[3,4]])

In [13]:
a==b

array([[ True,  True],
       [ True,  True]])

In [14]:
type(a) == type(b)

True

In [15]:
a is b

False

In [18]:
a = np.array([[1,2],[3,4]], dtype=np.int32)
b= np.asarray([[1,2],[3,4]], dtype=np.int32)
a is b

False

In [19]:
np.asarray(a, dtype=np.int32) is a

True

In [20]:
issubclass(np.matrix, np.ndarray)

True

In [21]:
a = [1, 2]
np.asanyarray(a)

array([1, 2])

In [22]:
b = np.mat([1,2])
b

matrix([[1, 2]])

In [23]:
np.asanyarray(b)

matrix([[1, 2]])

In [25]:
np.array(b, copy=False)

array([[1, 2]])

In [26]:
np.array(b, copy=True)

array([[1, 2]])

In [6]:
np.fromfunction(lambda i,j:i == j, (3,3), dtype=np.int32)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [7]:
np.fromfunction(lambda i,j:i+j, (3,3), dtype=np.int32)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [8]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000224032390C0>

In [10]:
np.fromiter(iterable, dtype=np.float32)

array([ 0.,  1.,  4.,  9., 16.], dtype=float32)

In [11]:
iterable = [x*x for x in range(5)]
iterable

[0, 1, 4, 9, 16]

In [12]:
np.fromiter(iterable, dtype=np.float32)

array([ 0.,  1.,  4.,  9., 16.], dtype=float32)

In [13]:
np.fromstring('abc sdhg ashdkj sidh', sep=' ')

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  """Entry point for launching an IPython kernel.


array([], dtype=float64)

In [16]:
np.fromstring('abc sdh dkj idh')

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


ValueError: string size must be a multiple of element size

In [18]:
np.fromstring('123 45 6')

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


array([5.5449225e-48])

In [19]:
np.fromstring('123 45 6', sep=' ')

array([123.,  45.,   6.])

In [20]:
np.fromstring('123,45,6', sep=',')

array([123.,  45.,   6.])

In [22]:
np.fromstring('123456')

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


ValueError: string size must be a multiple of element size

In [26]:
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
r = np.core.records.fromarrays([x1,x2,x3,x4])
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('f0', '<i4'), ('f1', '<U3'), ('f2', '<f8'), ('f3', '<f8')])

In [28]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
type(np.array(my_mat))

numpy.ndarray

In [34]:
range(1,5)

range(1, 5)

In [36]:
list(range(1,5))

[1, 2, 3, 4]

In [40]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [41]:
list(range(50,-1,5))

[]

In [42]:
list(range(50,-1,-5))

[50, 45, 40, 35, 30, 25, 20, 15, 10, 5, 0]

In [37]:
range(1,5.1)

TypeError: 'float' object cannot be interpreted as an integer

In [35]:
np.arange(1,5)

array([1, 2, 3, 4])

In [38]:
np.arange(1,5.1)

array([1., 2., 3., 4., 5.])

In [39]:
np.arange(1.1,5.1, 1.2)

array([1.1, 2.3, 3.5, 4.7])

In [43]:
np.arange(50,-1,5)

array([], dtype=int32)

In [44]:
np.arange(50,-1,-5)

array([50, 45, 40, 35, 30, 25, 20, 15, 10,  5,  0])

In [45]:
np.linspace(1,5.1, 20)

array([1.        , 1.21578947, 1.43157895, 1.64736842, 1.86315789,
       2.07894737, 2.29473684, 2.51052632, 2.72631579, 2.94210526,
       3.15789474, 3.37368421, 3.58947368, 3.80526316, 4.02105263,
       4.23684211, 4.45263158, 4.66842105, 4.88421053, 5.1       ])

In [46]:
np.linspace(1,5.1, 20.1)

TypeError: object of type <class 'float'> cannot be safely interpreted as an integer.

In [47]:
np.linspace(50,-1, 20)

array([50.        , 47.31578947, 44.63157895, 41.94736842, 39.26315789,
       36.57894737, 33.89473684, 31.21052632, 28.52631579, 25.84210526,
       23.15789474, 20.47368421, 17.78947368, 15.10526316, 12.42105263,
        9.73684211,  7.05263158,  4.36842105,  1.68421053, -1.        ])

In [48]:
np.logspace(1,5.1,20, base=10)

array([1.00000000e+01, 1.64357480e+01, 2.70133812e+01, 4.43985126e+01,
       7.29722764e+01, 1.19935395e+02, 1.97122792e+02, 3.23986054e+02,
       5.32495313e+02, 8.75195877e+02, 1.43844989e+03, 2.36419999e+03,
       3.88573952e+03, 6.38650355e+03, 1.04966963e+04, 1.72521055e+04,
       2.83551258e+04, 4.66037703e+04, 7.65967823e+04, 1.25892541e+05])

In [49]:
np.logspace(1,5.1,num=10, base=2)

array([ 2.        ,  2.74262154,  3.76098646,  5.15748123,  7.07250956,
        9.69860853, 13.29980634, 18.23816767, 25.01019576, 34.2967508 ])

In [51]:
np.logspace(1, 5.1, num=10, base=2, endpoint=False)

array([ 2.        ,  2.65737163,  3.53081199,  4.6913398 ,  6.23331664,
        8.28211939, 11.00433455, 14.6213032 , 19.42711815, 25.8125363 ])

In [52]:
np.logspace(1,5.1,num=10, base=2)

array([ 2.        ,  2.74262154,  3.76098646,  5.15748123,  7.07250956,
        9.69860853, 13.29980634, 18.23816767, 25.01019576, 34.2967508 ])

In [54]:
np.arange(0,100,5).reshape(10,2)

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [55]:
np.arange(0,100,5).reshape(10,-1)

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [58]:
x = np.arange(0,100,5).reshape(-1,2)
x

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55],
       [60, 65],
       [70, 75],
       [80, 85],
       [90, 95]])

In [59]:
np.diag(x)

array([ 0, 15])

In [61]:
x = np.arange(0,16).reshape(4,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
np.diag(x)

array([ 0,  5, 10, 15])

In [63]:
np.diag(x, k=1)

array([ 1,  6, 11])

In [65]:
np.diag(x, k=-1)

array([ 4,  9, 14])

In [66]:
np.diag(x, k=-2)

array([ 8, 13])

In [67]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [68]:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [69]:
np.diagflat([[1,2],[3,4]], 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [71]:
np.tri(3,3)

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [72]:
np.tri(3,3,-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [73]:
np.tril(3,3)

TypeError: tri() missing 1 required positional argument: 'N'

In [75]:
np.tril([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [76]:
np.triu([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9]])

In [78]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 1)

array([[1, 2, 0],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.random.rand(5)

array([0.22056368, 0.40424018, 0.34860477, 0.98622604, 0.67543201])

In [84]:
np.random.rand(5,5)

array([[0.98565781, 0.579884  , 0.17511623, 0.31314238, 0.78564646],
       [0.28905187, 0.22572836, 0.67925202, 0.84834306, 0.82153506],
       [0.07663809, 0.02752925, 0.47240373, 0.88255254, 0.4597353 ],
       [0.33033842, 0.92846221, 0.86381082, 0.28027025, 0.13213633],
       [0.71905404, 0.30641068, 0.06407906, 0.0587919 , 0.49063938]])

In [85]:
np.random.rand(5,5,1)

array([[[0.00146411],
        [0.8959377 ],
        [0.52936487],
        [0.31785791],
        [0.05314211]],

       [[0.42511065],
        [0.16310962],
        [0.12730486],
        [0.57032059],
        [0.47769731]],

       [[0.45937997],
        [0.00347383],
        [0.53880847],
        [0.60216669],
        [0.80348759]],

       [[0.95900377],
        [0.17630923],
        [0.41100945],
        [0.11353703],
        [0.84767496]],

       [[0.97586541],
        [0.07849838],
        [0.31348812],
        [0.16533238],
        [0.26392278]]])

In [80]:
np.random.randn(5)

array([ 0.25350712,  0.56980021, -0.85126768, -1.08279412,  2.24900938])

In [81]:
np.random.randn(5,5)

array([[ 2.43355625,  0.95425226, -1.52087355, -0.76977406, -0.11457037],
       [ 0.88723633, -0.97014945,  0.83604023, -0.53601901, -0.27586762],
       [-0.04006068,  1.01587175,  0.84344035,  1.05843927,  1.41758784],
       [-0.49562787,  0.28464332, -0.98153369, -2.09715309, -1.54168945],
       [ 0.02254512,  1.66786506,  1.32260933, -0.44018904, -0.32086245]])

In [82]:
np.random.randn(5,5,1)

array([[[-0.42234498],
        [-0.70020129],
        [-0.16730419],
        [-0.74915844],
        [ 0.34312586]],

       [[-2.47751093],
        [-0.08796459],
        [ 0.22800488],
        [-1.80584633],
        [-0.2037773 ]],

       [[-0.24067619],
        [-0.28065536],
        [-0.41701576],
        [ 0.25568896],
        [ 1.05119189]],

       [[ 1.57266996],
        [ 1.87625411],
        [ 0.66506422],
        [ 1.89677848],
        [ 0.35670628]],

       [[ 2.2774225 ],
        [-0.10218964],
        [-0.76017456],
        [ 0.32750294],
        [ 0.75666587]]])

In [86]:
np.random.randint(5)

3

In [ ]:
np.random.randint(5)

In [87]:
np.random.randint(5,5)

ValueError: low >= high

In [88]:
np.random.randint(1,5)

1

In [89]:
np.random.randint(1,5,20)

array([3, 3, 4, 4, 2, 2, 3, 4, 1, 2, 4, 4, 4, 4, 3, 4, 2, 1, 4, 1])

In [92]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,-19878)
a

array([35, 28, 56, 45, 52, 22, 54, 84, 29, 34, 64, 24, 83, 95, 79, 26, 46,
       98, 40, 84,  8, 33, 73, 85,  3, 48, 16, 11, 25, 32])

In [93]:
b

array([[[35, 28, 56, 45, 52],
        [22, 54, 84, 29, 34],
        [64, 24, 83, 95, 79]],

       [[26, 46, 98, 40, 84],
        [ 8, 33, 73, 85,  3],
        [48, 16, 11, 25, 32]]])

In [94]:
c

array([[35, 28, 56, 45, 52],
       [22, 54, 84, 29, 34],
       [64, 24, 83, 95, 79],
       [26, 46, 98, 40, 84],
       [ 8, 33, 73, 85,  3],
       [48, 16, 11, 25, 32]])

In [111]:
a = ri(1,100,30).reshape(6,-2)
a

array([[30, 44, 43, 78, 83],
       [17, 80, 34, 98, 56],
       [22, 18, 25, 56, 59],
       [85, 56, 13, 70, 38],
       [16, 14,  5, 95, 30],
       [68, 52, 46, 54, 78]])

In [102]:
np.sort(a)

array([[ 5, 26, 26, 41, 90],
       [10, 51, 60, 90, 94],
       [27, 34, 60, 72, 94],
       [ 8, 17, 18, 43, 51],
       [ 6, 20, 56, 62, 76],
       [26, 70, 79, 80, 85]])

In [103]:
np.sort(a, axis=1)

array([[ 5, 26, 26, 41, 90],
       [10, 51, 60, 90, 94],
       [27, 34, 60, 72, 94],
       [ 8, 17, 18, 43, 51],
       [ 6, 20, 56, 62, 76],
       [26, 70, 79, 80, 85]])

In [104]:
np.sort(a, axis=0)

array([[ 5,  8,  6, 17, 18],
       [20, 60, 10, 26, 41],
       [26, 60, 26, 56, 51],
       [34, 62, 27, 70, 72],
       [51, 79, 43, 94, 76],
       [90, 90, 80, 94, 85]])

In [107]:
a.sort()

In [105]:
np.max(a)

94

In [106]:
a.max()

94

In [112]:
a

array([[30, 44, 43, 78, 83],
       [17, 80, 34, 98, 56],
       [22, 18, 25, 56, 59],
       [85, 56, 13, 70, 38],
       [16, 14,  5, 95, 30],
       [68, 52, 46, 54, 78]])

In [113]:
a.argmax()

8

In [114]:
a.argmax(axis=1)

array([4, 3, 4, 0, 3, 4], dtype=int64)

In [115]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
arr[1:4]

array([1, 2, 3])

In [117]:
arr[0:7:2]

array([0, 2, 4, 6])

In [118]:
arr[0:7:-2]

array([], dtype=int32)

In [119]:
arr[7:0:-2]

array([7, 5, 3, 1])

In [124]:
arr[0,1,2]

IndexError: too many indices for array

In [125]:
arr[[0,1,2]]

array([0, 1, 2])

In [126]:
arr[0:3]

array([0, 1, 2])

In [159]:
mat = np.array(ri(10,100,30)).reshape(3,5,2)
mat

array([[[96, 25],
        [35, 67],
        [55, 48],
        [29, 29],
        [30, 19]],

       [[40, 76],
        [55, 56],
        [87, 58],
        [84, 59],
        [84, 83]],

       [[31, 60],
        [57, 21],
        [26, 94],
        [98, 64],
        [93, 18]]])

In [129]:
mat[0][0]

array([49, 97])

In [130]:
mat[0][0][0]

49

In [132]:
mat[0:3][0][0]

array([49, 97])

In [133]:
mat[0:3,[0][0]]

array([[49, 97],
       [81, 69],
       [56, 12]])

In [135]:
mat[0:3,[0]]

array([[[49, 97]],

       [[81, 69]],

       [[56, 12]]])

In [136]:
mat[0:3,[0,1]]

array([[[49, 97],
        [69, 23]],

       [[81, 69],
        [32, 10]],

       [[56, 12],
        [55, 12]]])

In [161]:
mat

array([[[96, 25],
        [35, 67],
        [55, 48],
        [29, 29],
        [30, 19]],

       [[40, 76],
        [55, 56],
        [87, 58],
        [84, 59],
        [84, 83]],

       [[31, 60],
        [57, 21],
        [26, 94],
        [98, 64],
        [93, 18]]])

In [163]:
mat[0:3][:,1]

array([[35, 67],
       [55, 56],
       [57, 21]])

In [168]:
mat[0:3,[1,0]]

array([[12, 11],
       [22, 21],
       [32, 31]])

In [152]:
mat[0:3][0][1]

array([69, 23])

In [156]:
mat = np.array(ri(10,100,15)).reshape(3,5)
mat

array([[67, 42, 62, 99, 82],
       [20, 28, 52, 82, 76],
       [52, 57, 30, 38, 77]])

In [157]:
mat[mat>50]

array([67, 62, 99, 82, 52, 82, 76, 52, 57, 77])

In [164]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
mat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [165]:
mat[:2,:2]

array([[11, 12],
       [21, 22]])

In [166]:
mat[:,0]

array([11, 21, 31])

In [169]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [170]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [171]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [172]:
mat

array([[1000,   12,   13],
       [  21,   22,   23],
       [  31,   32,   33]])

In [173]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)



Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [174]:
mat_slice2 = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)



Sliced matrix
[[1000   12]
 [  21   22]]


In [175]:
print ("\nChange the sliced matrix")
mat_slice2[0,0] = 1000
print (mat_slice2)



Change the sliced matrix
[[1000   12]
 [  21   22]]


In [176]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [177]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[9 2 5]
 [5 5 3]
 [6 9 9]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[3 3 5]
 [8 1 5]
 [2 6 2]]


#One to one multiplication

In [178]:
mat1*mat2

array([[27,  6, 25],
       [40,  5, 15],
       [12, 54, 18]])

#matrix multiplication

In [179]:
mat1@mat2

array([[ 53,  59,  65],
       [ 61,  38,  56],
       [108,  81,  93]])

In [180]:
mat1/0

C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [181]:
mat1+100

array([[109, 102, 105],
       [105, 105, 103],
       [106, 109, 109]])

In [182]:
start = np.zeros((4,4))
start= start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [196]:
row_addition = np.array([1,2,3,4])
row_addition

array([1, 2, 3, 4])

In [189]:
start+row_addition

array([[101., 102., 103., 104.],
       [101., 102., 103., 104.],
       [101., 102., 103., 104.],
       [101., 102., 103., 104.]])

In [194]:
row_addition = np.array([[1,2,3,4]])
row_addition

array([[1, 2, 3, 4]])

In [195]:
start+row_addition

array([[101., 102., 103., 104.],
       [101., 102., 103., 104.],
       [101., 102., 103., 104.],
       [101., 102., 103., 104.]])

In [191]:
col_addition = np.array([1,2,3,4])
col_addition.T

array([1, 2, 3, 4])

In [192]:
col_addition = np.array([[1,2,3,4]])
col_addition.T

array([[1],
       [2],
       [3],
       [4]])

In [198]:
start+col_addition.T

array([[101., 101., 101., 101.],
       [102., 102., 102., 102.],
       [103., 103., 103., 103.],
       [104., 104., 104., 104.]])

In [200]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+add_scalar)

[[200. 200. 200. 200.]
 [200. 200. 200. 200.]
 [200. 200. 200. 200.]
 [200. 200. 200. 200.]]


In [202]:
# this will just broadcast in both dimensions
add_scalar = np.array([100,200,300,400])  
print(start+add_scalar)

[[200. 300. 400. 500.]
 [200. 300. 400. 500.]
 [200. 300. 400. 500.]
 [200. 300. 400. 500.]]


In [203]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)

In [204]:
np.sqrt(mat1)

array([[2.23606798, 1.41421356, 2.23606798],
       [1.        , 2.        , 1.73205081],
       [1.41421356, 1.41421356, 1.        ]])

In [205]:
np.exp(mat2)

array([[5.45981500e+01, 8.10308393e+03, 8.10308393e+03],
       [2.00855369e+01, 2.00855369e+01, 5.45981500e+01],
       [2.71828183e+00, 2.00855369e+01, 5.45981500e+01]])

In [206]:
np.log10(mat1)

array([[0.69897   , 0.30103   , 0.69897   ],
       [0.        , 0.60205999, 0.47712125],
       [0.30103   , 0.30103   , 0.        ]])

In [207]:
np.log2(mat1)

array([[2.32192809, 1.        , 2.32192809],
       [0.        , 2.        , 1.5849625 ],
       [1.        , 1.        , 0.        ]])

In [208]:
np.log8(mat1)

AttributeError: module 'numpy' has no attribute 'log8'

In [209]:
np.fmod(mat1,mat2)

array([[1, 2, 5],
       [1, 1, 3],
       [0, 2, 1]], dtype=int32)

In [210]:
mat1%mat2

array([[1, 2, 5],
       [1, 1, 3],
       [0, 2, 1]], dtype=int32)

In [211]:
np.pi

3.141592653589793

In [212]:
pi

NameError: name 'pi' is not defined

In [214]:
np.linspace(0,np.pi*20,100)

array([ 0.        ,  0.63466518,  1.26933037,  1.90399555,  2.53866073,
        3.17332591,  3.8079911 ,  4.44265628,  5.07732146,  5.71198664,
        6.34665183,  6.98131701,  7.61598219,  8.25064737,  8.88531256,
        9.51997774, 10.15464292, 10.7893081 , 11.42397329, 12.05863847,
       12.69330365, 13.32796883, 13.96263402, 14.5972992 , 15.23196438,
       15.86662956, 16.50129475, 17.13595993, 17.77062511, 18.40529029,
       19.03995548, 19.67462066, 20.30928584, 20.94395102, 21.57861621,
       22.21328139, 22.84794657, 23.48261175, 24.11727694, 24.75194212,
       25.3866073 , 26.02127248, 26.65593767, 27.29060285, 27.92526803,
       28.55993321, 29.1945984 , 29.82926358, 30.46392876, 31.09859394,
       31.73325913, 32.36792431, 33.00258949, 33.63725467, 34.27191986,
       34.90658504, 35.54125022, 36.1759154 , 36.81058059, 37.44524577,
       38.07991095, 38.71457614, 39.34924132, 39.9839065 , 40.61857168,
       41.25323687, 41.88790205, 42.52256723, 43.15723241, 43.79